### ISSUE TITLE
Error installing pynput package using pip

### ISSUE THREAD

**Issue by flyguy712** [OpenAdaptAI/OpenAdapt#124]
I am encountering this error when trying to run the `pip install -r requirements.txt` command in terminal. 

Operating system: MacOS(13.1)
Interpreter: Python 3.10

### Reproduction steps

1. git clone https://github.com/MLDSAI/OpenAdapt.git
2. cd OpenAdapt
3. python3.10 -m venv .venv
4. source .venv/bin/activate
5. pip install wheel
6. **Bug:** pip install -r requirements.txt

### Logs
```
(.venv) taylorhorsager@Taylors-MacBook-Air OpenAdapt % pip install git+https://github.com/abrichr/pynput.git

Collecting git+https://github.com/abrichr/pynput.git
  Cloning https://github.com/abrichr/pynput.git to /private/var/folders/kx/ldt2q_ks6kn370mkg2fryvvh0000gn/T/pip-req-build-fx191rh6
  Running command git clone --filter=blob:none --quiet https://github.com/abrichr/pynput.git /private/var/folders/kx/ldt2q_ks6kn370mkg2fryvvh0000gn/T/pip-req-build-fx191rh6
  Resolved https://github.com/abrichr/pynput.git to commit 5d7256761b3cf6f01758c2d7d6a877d8facf79bb
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in ./.venv/lib/python3.10/site-packages (from pynput==1.7.6) (1.16.0)
Requirement already satisfied: pyobjc-framework-ApplicationServices>=8.0 in ./.venv/lib/python3.10/site-packages (from pynput==1.7.6) (9.1.1)
Requirement already satisfied: pyobjc-framework-Quartz>=8.0 in ./.venv/lib/python3.10/site-packages (from pynput==1.7.6) (9.1.1)
Requirement already satisfied: pyobjc-core>=9.1.1 in ./.venv/lib/python3.10/site-packages (from pyobjc-framework-ApplicationServices>=8.0->pynput==1.7.6) (9.1.1)
Requirement already satisfied: pyobjc-framework-Cocoa>=9.1.1 in ./.venv/lib/python3.10/site-packages (from pyobjc-framework-ApplicationServices>=8.0->pynput==1.7.6) (9.1.1)
Building wheels for collected packages: pynput
  Building wheel for pynput (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kx/ldt2q_ks6kn370mkg2fryvvh0000gn/T/pip-req-build-fx191rh6/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 95, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
          os.mkdir(destination_eggdir)
      FileExistsError: [Errno 17] File exists: '/private/var/folders/kx/ldt2q_ks6kn370mkg2fryvvh0000gn/T/pip-req-build-fx191rh6/.eggs/wrapt-1.15.0-py3.10-macosx-10.9-universal2.egg'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynput
  Running setup.py clean for pynput
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kx/ldt2q_ks6kn370mkg2fryvvh0000gn/T/pip-req-build-fx191rh6/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 95, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/taylorhorsager/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
          os.mkdir(destination_eggdir)
      FileExistsError: [Errno 17] File exists: '/private/var/folders/kx/ldt2q_ks6kn370mkg2fryvvh0000gn/T/pip-req-build-fx191rh6/.eggs/wrapt-1.15.0-py3.10-macosx-10.9-universal2.egg'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pynput
Failed to build pynput
ERROR: Could not build wheels for pynput, which is required to install pyproject.toml-based projects
```

### Troubleshooting

- I have tried running `pip cache purge` 
- I have tried installing the modified version of pynput directly from `pip install git+https://github.com/abrichr/pynput.git`
- After running `pip install --upgrade 'setuptools<42'` this is the result:

```
taylorhorsager@Taylors-MacBook-Air ~ % pip install --upgrade 'setuptools<42'
Collecting setuptools<42
  Downloading setuptools-41.6.0-py2.py3-none-any.whl (582 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 582.9/582.9 kB 8.4 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.4.0
    Uninstalling setuptools-57.4.0:
      Successfully uninstalled setuptools-57.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyinstaller 5.10.1 requires setuptools>=42.0.0, but you have setuptools 41.6.0 which is incompatible.
Successfully installed setuptools-41.6.0
```

**Comment by abrichr** [comment]
Please try the solutions mentioned in this thread: https://github.com/MLDSAI/OpenAdapt/issues/40

**Comment by abrichr** [comment]
@flyguy712 are you still experiencing this issue?

**Comment by abrichr** [comment]
@flyguy712 any update here?

**Comment by flyguy712** [comment]
@abrichr thanks for following up on this. Took me a few weeks to get back to it... but just did and got it to work!
