### ISSUE TITLE
[Bug]: Error while parsing completion str in get_next_action_event in  StatefulReplayStrategy

### ISSUE THREAD

**Issue by FFFiend** [OpenAdaptAI/OpenAdapt#329]
### Describe the bug

Whenever the output from GPT-3.5-Turbo or GPT-4 was being evaluated you would get the following error:
```
2023-06-28 15:43:59.742 | WARNING  | openadapt.strategies.stateful:get_action_dict_from_completion:139 - exc=SyntaxError('invalid syntax', ('<string>', 1, 20, "active_action_dicts=[{'name': 'click', 'mouse_x': 514.92578125, 'mouse_y': 269.47265625, 'mouse_button_name': 'left', 'mouse_pressed': True, 'element_state': {}}, {'name': 'click', 'mouse_x': 514.92578125, 'mouse_y': 269.47265625, 'mouse_button_name': 'left', 'mouse_pressed': False, 'element_state': {}}]", 1, 21))
2023-06-28 15:43:59.742 | DEBUG    | openadapt.strategies.stateful:get_next_action_event:129 - =
None
Traceback (most recent call last):
  File "/Users/owaiszahid/Desktop/state/OpenAdapt/tests/openadapt/test_stateful.py", line 47, in <module>
    test_active_window_no_diff()
  File "/Users/owaiszahid/Desktop/state/OpenAdapt/tests/openadapt/test_stateful.py", line 38, in test_active_window_no_diff
    test_action_dict = test_obj.get_next_action_event(Screenshot(),test_window_dict)
  File "/Users/owaiszahid/Desktop/state/OpenAdapt/openadapt/strategies/stateful.py", line 130, in get_next_action_event
    active_action = models.ActionEvent.from_children(active_action_dicts)
  File "/Users/owaiszahid/Desktop/state/OpenAdapt/openadapt/models.py", line 206, in from_children
    children = [
TypeError: 'NoneType' object is not iterable
```

### To Reproduce

Standard set up, simply initialize the StatefulReplayStrategy class in an object with a recording, and call ```get_next_action_event``` on a/multiple WindowEvents.

**Comment by FFFiend** [comment]
To fix: edit line ```127``` in ```stateful.py``` as follows:

```
        completion = self.get_completion(prompt, system_message)[21:-1]
```

**Comment by FFFiend** [comment]
Actually this is not the right fix, sometimes the model may not adhere to the same format and it ends up slicing the string incorrectly.

**Comment by abrichr** [comment]
Closing as part of architecture transition. Legacy frozen at v0.46.0. See PR #960.
