### ISSUE TITLE
Test longer recordings

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#351]
### Feature request

The README currently states:

```
recording should be short (i.e. under a minute), as they are somewhat memory intensive, and there is currently an https://github.com/MLDSAI/OpenAdapt/issues/5 describing a possible memory leak
```

Let's test this to see if it's still the case, and if not let's remove this from the README.

### Motivation

Since https://github.com/OpenAdaptAI/OpenAdapt/pull/270 was merged this may no longer be the case.

**Comment by KrishPatel13** [comment]
I will be testing longer recording 5min and 10min one tonight. And then I will be pasting the transcript of the terminal here.

I there anything else I need to take care of ?

**Comment by 0dm** [comment]
tested 3 minutes - Apple M1 16GB - Ventura 13.3

<img width="1316" alt="image" src="https://github.com/OpenAdaptAI/OpenAdapt/assets/57018940/ce7158db-2e15-4616-bdf2-30ac2d850789">

result (visualize):
```sh
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=821923), 'exception': (type=<class 'AssertionError'>, value=AssertionError((<function merge_consecutive_mouse_move_events at 0x1384267a0>, ActionEvent(id=2287, name='type', timestamp=1688506304.7285082, recording_timestamp=1688502773.066591, screenshot_timestamp=1688506324.8797328, window_event_timestamp=1688506306.0636973, text='t-e-s-t-i-n-g', canonical_text='t-e-s-t-i-n-g'), ActionEvent(id=2288, name='type', timestamp=1688506293.187175, recording_timestamp=1688502773.066591, screenshot_timestamp=1688506325.8940156, window_event_timestamp=1688506306.0636973, text='<space>', canonical_text='<49>'))), traceback=<traceback object at 0x13b82e6c0>), 'extra': {}, 'file': (name='events.py', path='/Users/aaron/Documents/GitHub/OpenAdapt/openadapt/events.py'), 'function': 'process_events', 'level': (name='ERROR', no=40, icon='❌'), 'line': 620, 'message': "(<function merge_consecutive_mouse_move_events at 0x1384267a0>, ActionEvent(id=2287, name='type', timestamp=1688506304.7285082, recording_timestamp=1688502773.066591, screenshot_timestamp=1688506324.8797328, window_event_timestamp=1688506306.0636973, text='t-e-s-t-i-n-g', canonical_text='t-e-s-t-i-n-g'), ActionEvent(id=2288, name='type', timestamp=1688506293.187175, recording_timestamp=1688502773.066591, screenshot_timestamp=1688506325.8940156, window_event_timestamp=1688506306.0636973, text='<space>', canonical_text='<49>'))", 'module': 'events', 'name': 'openadapt.events', 'process': (id=6146, name='MainProcess'), 'thread': (id=8026102592, name='MainThread'), 'time': datetime(2023, 7, 4, 16, 40, 47, 317630, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=72000), 'EDT'))}
Traceback (most recent call last):
  File "/Users/aaron/Documents/GitHub/OpenAdapt/openadapt/events.py", line 616, in process_events
    assert prev_event.timestamp <= event.timestamp, (
AssertionError: (<function merge_consecutive_mouse_move_events at 0x1384267a0>, ActionEvent(id=2287, name='type', timestamp=1688506304.7285082, recording_timestamp=1688502773.066591, screenshot_timestamp=1688506324.8797328, window_event_timestamp=1688506306.0636973, text='t-e-s-t-i-n-g', canonical_text='t-e-s-t-i-n-g'), ActionEvent(id=2288, name='type', timestamp=1688506293.187175, recording_timestamp=1688502773.066591, screenshot_timestamp=1688506325.8940156, window_event_timestamp=1688506306.0636973, text='<space>', canonical_text='<49>'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Library/Caches/pypoetry/virtualenvs/openadapt-OrpD_qgG-py3.10/lib/python3.10/site-packages/loguru/_handler.py", line 175, in emit
    self._queue.put(str_record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/Users/aaron/Library/Caches/pypoetry/virtualenvs/openadapt-OrpD_qgG-py3.10/lib/python3.10/site-packages/loguru/_recattrs.py", line 73, in __reduce__
    pickle.dumps(self.value)
  File "/Users/aaron/Library/Caches/pypoetry/virtualenvs/openadapt-OrpD_qgG-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 517, in __getstate__
    state_dict["manager"] = self.manager._serialize(self, state_dict)
  File "/Users/aaron/Library/Caches/pypoetry/virtualenvs/openadapt-OrpD_qgG-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/instrumentation.py", line 430, in _serialize
    return _SerializeManager(state, state_dict)
  File "/Users/aaron/Library/Caches/pypoetry/virtualenvs/openadapt-OrpD_qgG-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/instrumentation.py", line 486, in __init__
    manager.dispatch.pickle(state, d)
RecursionError: maximum recursion depth exceeded while calling a Python object
--- End of logging error ---
> /Users/aaron/Documents/GitHub/OpenAdapt/openadapt/events.py(614)process_events()
    613         # TODO: keep events in which window_event_timestamp is updated
--> 614         for prev_event, event in zip(action_events, action_events[1:]):
    615   
    ```

**Comment by abrichr** [comment]
Closing as part of architecture transition. Legacy frozen at v0.46.0. See PR #960.
