### ISSUE TITLE
[Bug]: Unhandled Exception (TypeError) in record

### ISSUE THREAD

**Issue by dianzrong** [OpenAdaptAI/OpenAdapt#363]
### Describe the bug

Got a TypeError when running record

Output:
```
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - CACHE_DIR_PATH=.cache
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - CACHE_ENABLED=True
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - CACHE_VERBOSITY=0
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - DB_ECHO=False
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - DB_FNAME=openadapt.db
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - OPENAI_API_KEY=********************
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - OPENAI_MODEL_NAME=gpt-3.5-turbo
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - RECORD_READ_ACTIVE_ELEMENT_STATE=False
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - REPLAY_STRIP_ELEMENT_STATE=True
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - IGNORE_WARNINGS=False
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - ACTION_TEXT_SEP=-
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - ACTION_TEXT_NAME_PREFIX=<
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - ACTION_TEXT_NAME_SUFFIX=>
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - SCRUB_ENABLED=True
2023-07-07 15:10:10.705 | INFO     | openadapt.config:<module>:110 - SCRUB_CHAR=*
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - SCRUB_LANGUAGE=en
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - SCRUB_FILL_COLOR=255
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - SCRUB_CONFIG_TRF={'nlp_engine_name': 'spacy', 'models': [{'lang_code': 'en', 'model_name': 'en_core_web_trf'}]}
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - SCRUB_IGNORE_ENTITIES=['DATE_TIME', 'URL']
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - SCRUB_KEYS_HTML=['text', 'canonical_text', 'title', 'state', 'task_description', 'key_char', 'canonical_key_char', 'key_vk', 'children']
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - ROOT_DIRPATH=/Users/d/OpenAdapt
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - DB_FPATH=/Users/d/OpenAdapt/openadapt.db
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - DB_URL=sqlite:////Users/d/OpenAdapt/openadapt.db
2023-07-07 15:10:10.706 | INFO     | openadapt.config:<module>:110 - DIRNAME_PERFORMANCE_PLOTS=performance
2023-07-07 15:10:11.627 | INFO     | __main__:record:518 - task_description='characters'
2023-07-07 15:10:11.722 | INFO     | __main__:create_recording:460 - recording=Recording(id=13, timestamp=1688757011.627622, monitor_width=1440, monitor_height=900, double_click_interval_seconds=0.5, double_click_distance_pixels=5, platform='darwin', task_description='characters')
2023-07-07 15:10:11.736 | INFO     | __main__:read_window_events:366 - starting
2023-07-07 15:10:11.740 | INFO     | __main__:read_screen_events:340 - starting
2023-07-07 15:10:11.747 | INFO     | __main__:process_events:72 - starting
2023-07-07 15:10:11.887 | INFO     | __main__:read_window_events:384 - _window_data={'title': 'Code __init__.py — OpenAdapt', 'left': 508, 'top': 25, 'width': 932, 'height': 875, 'window_id': 94}
2023-07-07 15:10:14.347 | INFO     | __mp_main__:write_events:211 - event_type='screen' starting
2023-07-07 15:10:14.348 | INFO     | __mp_main__:write_events:211 - event_type='action' starting
2023-07-07 15:10:14.348 | INFO     | __mp_main__:write_events:211 - event_type='window' starting
2023-07-07 15:10:14.356 | INFO     | __mp_main__:performance_stats_writer:414 - performance stats writer starting
Unhandled exception in listener callback
Traceback (most recent call last):
  File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/pynput/_util/__init__.py", line 230, in inner
    return f(self, *args, **kwargs)
  File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/pynput/_util/darwin.py", line 286, in _handler
    self._handle(proxy, event_type, event, refcon, is_injected)
  File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/pynput/keyboard/_darwin.py", line 291, in _handle
    self.on_press(self._SPECIAL_KEYS[key])
  File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/pynput/_util/__init__.py", line 146, in inner
    if f(*args) is False:
TypeError: read_keyboard_events.<locals>.on_press() missing 1 required positional argument: 'injected'
2023-07-07 15:10:21.856 | WARNING  | openadapt.window._macos:get_active_window_state:42 - exc=TypeError('Cannot pickle Objective-C objects')
2023-07-07 15:10:21.857 | INFO     | __main__:read_window_events:384 - _window_data={'title': 'Google Chrome Issues · OpenAdaptAI/OpenAdapt', 'left': 0, 'top': 25, 'width': 886, 'height': 875, 'window_id': 3042}
2023-07-07 15:10:21.942 | INFO     | __main__:read_window_events:384 - _window_data={'title': 'Code __init__.py — OpenAdapt', 'left': 508, 'top': 25, 'width': 932, 'height': 875, 'window_id': 94}
^C2023-07-07 15:10:23.655 | INFO     | __main__:record:627 - joining...
2023-07-07 15:10:23.655 | INFO     | __mp_main__:write_events:221 - event_type='action' done
2023-07-07 15:10:23.655 | INFO     | __mp_main__:write_events:221 - event_type='window' done
2023-07-07 15:10:23.671 | INFO     | __main__:read_screen_events:347 - done
2023-07-07 15:10:23.672 | INFO     | __main__:process_events:126 - done
2023-07-07 15:10:38.356 | INFO     | __mp_main__:write_events:221 - event_type='screen' done
2023-07-07 15:10:38.483 | INFO     | __mp_main__:performance_stats_writer:428 - performance stats writer done
2023-07-07 15:10:38.483 | INFO     | __main__:record:642 - saved recording_timestamp=1688757011.627622
```

### To Reproduce

I use MacOS
1. python -m openadapt.record "characters"
2. (after the 3 event writers have started) click the f8 key

**Comment by dianzrong** [comment]
Interestingly enough, the same error occurs for f10-12 but not f1-7

**Comment by abrichr** [comment]
@dianzrong thank you for reporting! Can you please confirm that you are using the forked version of `pynput`?

**Comment by dianzrong** [comment]
@abrichr I am using the forked version as specified in the pyproject.toml

**Comment by ayewo** [comment]
@dianzrong Based on the output you shared, it seems that app window for VSCode was in focus when the bug occurred immediately after you hit the F8 key.

When I tried now, I am unable to reproduce it with VSCode in focus. 
1. Can you still reproduce the bug with the latest code?
2. If yes, please share what version of macOS are you on.

**Comment by dianzrong** [comment]
@ayewo 

1. Yes I am still able to reproduce the bug with the latest code 
```2023-07-28 13:06:05.885 | INFO     | openadapt.config:<module>:176 - STOP_STRS=['oa.stop']
2023-07-28 13:06:05.886 | INFO     | openadapt.config:<module>:176 - SPECIAL_CHAR_STOP_SEQUENCES=[['ctrl', 'ctrl', 'ctrl']]
2023-07-28 13:06:05.886 | INFO     | openadapt.config:<module>:176 - STOP_SEQUENCES=[['o', 'a', '.', 's', 't', 'o', 'p'], ['ctrl', 'ctrl', 'ctrl']]
2023-07-28 13:06:05.886 | INFO     | openadapt.config:<module>:176 - CACHE_DIR_PATH=.cache
2023-07-28 13:06:05.886 | INFO     | openadapt.config:<module>:176 - CACHE_ENABLED=True
2023-07-28 13:06:05.886 | INFO     | openadapt.config:<module>:176 - CACHE_VERBOSITY=0
2023-07-28 13:06:05.886 | INFO     | openadapt.config:<module>:176 - DB_ECHO=False
2023-07-28 13:06:05.886 | INFO     | openadapt.config:<module>:176 - DB_FNAME=openadapt.db
2023-07-28 13:06:05.887 | INFO     | openadapt.config:<module>:176 - OPENAI_API_KEY=**********************************************OthZh
2023-07-28 13:06:05.887 | INFO     | openadapt.config:<module>:176 - OPENAI_MODEL_NAME=gpt-3.5-turbo
2023-07-28 13:06:05.887 | INFO     | openadapt.config:<module>:176 - RECORD_READ_ACTIVE_ELEMENT_STATE=False
2023-07-28 13:06:05.887 | INFO     | openadapt.config:<module>:176 - REPLAY_STRIP_ELEMENT_STATE=True
2023-07-28 13:06:05.887 | INFO     | openadapt.config:<module>:176 - IGNORE_WARNINGS=False
2023-07-28 13:06:05.888 | INFO     | openadapt.config:<module>:176 - ACTION_TEXT_SEP=-
2023-07-28 13:06:05.888 | INFO     | openadapt.config:<module>:176 - ACTION_TEXT_NAME_PREFIX=<
2023-07-28 13:06:05.888 | INFO     | openadapt.config:<module>:176 - ACTION_TEXT_NAME_SUFFIX=>
2023-07-28 13:06:05.888 | INFO     | openadapt.config:<module>:176 - SCRUB_ENABLED=False
2023-07-28 13:06:05.888 | INFO     | openadapt.config:<module>:176 - SCRUB_CHAR=*
2023-07-28 13:06:05.888 | INFO     | openadapt.config:<module>:176 - SCRUB_LANGUAGE=en
2023-07-28 13:06:05.889 | INFO     | openadapt.config:<module>:176 - SCRUB_FILL_COLOR=255
2023-07-28 13:06:05.889 | INFO     | openadapt.config:<module>:176 - SCRUB_CONFIG_TRF={'nlp_engine_name': 'spacy', 'models': [{'lang_code': 'en', 'model_name': 'en_core_web_trf'}]}
2023-07-28 13:06:05.889 | INFO     | openadapt.config:<module>:176 - SCRUB_IGNORE_ENTITIES=['DATE_TIME', 'URL']
2023-07-28 13:06:05.890 | INFO     | openadapt.config:<module>:176 - SCRUB_KEYS_HTML=['text', 'canonical_text', 'title', 'state', 'task_description', 'key_char', 'canonical_key_char', 'key_vk', 'children']
2023-07-28 13:06:05.890 | INFO     | openadapt.config:<module>:176 - PLOT_PERFORMANCE=True
2023-07-28 13:06:05.890 | INFO     | openadapt.config:<module>:176 - SAVE_SCREENSHOT_DIFF=False
2023-07-28 13:06:05.890 | INFO     | openadapt.config:<module>:176 - ROOT_DIRPATH=/Users/d/OpenAdapt
2023-07-28 13:06:05.890 | INFO     | openadapt.config:<module>:176 - DB_FPATH=/Users/d/OpenAdapt/openadapt.db
2023-07-28 13:06:05.891 | INFO     | openadapt.config:<module>:176 - DB_URL=sqlite:////Users/d/OpenAdapt/openadapt.db
2023-07-28 13:06:05.891 | INFO     | openadapt.config:<module>:176 - DIRNAME_PERFORMANCE_PLOTS=performance
2023-07-28 13:06:08.223 | INFO     | __main__:wrapper_logging:122 -  -> Enter: record(te)
2023-07-28 13:06:08.224 | INFO     | __main__:record:816 - task_description='te'
2023-07-28 13:06:08.224 | INFO     | __main__:wrapper_logging:122 -  -> Enter: create_recording(te)
2023-07-28 13:06:08.313 | INFO     | __main__:create_recording:674 - recording=Recording(id=43, timestamp=1690563968.225089, monitor_width=1440, monitor_height=900, double_click_interval_seconds=0.5, double_click_distance_pixels=5, platform='darwin', task_description='te')
2023-07-28 13:06:08.313 | INFO     | __main__:wrapper_logging:126 -  <- Leave: create_recording(Recording(id=43, timestamp=1690563968.225089, monitor_width=1440, monitor_height=900, double_click_interval_seconds=0.5, double_click_distance_pixels=5, platform='darwin', task_description='te'))
2023-07-28 13:06:08.327 | INFO     | __main__:wrapper_logging:122 -  -> Enter: read_window_events(<queue.Queue object at 0x11af7f400>, <multiprocessing.synchronize.Event object at 0x11b314430>, 1690563968.225089)
2023-07-28 13:06:08.327 | INFO     | __main__:read_window_events:535 - Starting
2023-07-28 13:06:08.331 | INFO     | __main__:read_screen_events:511 - Starting
2023-07-28 13:06:08.334 | INFO     | __main__:wrapper_logging:122 -  -> Enter: process_events(<queue.Queue object at 0x11af7f400>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x11af7ff10>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x11b2b5a80>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x11b2b4b20>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x11b2b5750>, 1690563968.225089, <multiprocessing.synchronize.Event object at 0x11b314430>)
2023-07-28 13:06:08.335 | INFO     | __main__:process_events:181 - Starting
2023-07-28 13:06:08.548 | INFO     | __main__:read_window_events:554 - _window_data={'title': 'Terminal OpenAdapt — poetry shell ▸ Python — 109×44', 'left': 496, 'top': 69, 'width': 773, 'height': 651, 'window_id': 255}
2023-07-28 13:06:14.120 | INFO     | __mp_main__:wrapper_logging:122 -  -> Enter: performance_stats_writer(<openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x102f13f40>, 1690563968.225089, <multiprocessing.synchronize.Event object at 0x138212230>)
2023-07-28 13:06:14.124 | INFO     | __mp_main__:performance_stats_writer:583 - Performance stats writer starting
2023-07-28 13:06:14.268 | INFO     | __mp_main__:memory_writer:617 - Memory writer starting
2023-07-28 13:06:14.280 | INFO     | __mp_main__:wrapper_logging:122 -  -> Enter: write_events(screen, <function write_screen_event at 0x124101b40>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x100c8ff40>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x124112230>, 1690563968.225089, <multiprocessing.synchronize.Event object at 0x124110b80>, <multiprocessing.connection.Connection object at 0x124110ee0>)
2023-07-28 13:06:14.281 | INFO     | __mp_main__:write_events:319 - event_type='screen' starting
2023-07-28 13:06:14.294 | INFO     | __mp_main__:wrapper_logging:122 -  -> Enter: write_events(action, <function write_action_event at 0x12e419990>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x1012f3f40>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x12e42a230>, 1690563968.225089, <multiprocessing.synchronize.Event object at 0x12e428b80>, <multiprocessing.connection.Connection object at 0x12e428ee0>)
2023-07-28 13:06:14.295 | INFO     | __mp_main__:write_events:319 - event_type='action' starting
2023-07-28 13:06:14.352 | INFO     | __mp_main__:wrapper_logging:122 -  -> Enter: write_events(window, <function write_window_event at 0x112901bd0>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x100f37f40>, <openadapt.extensions.synchronized_queue.SynchronizedQueue object at 0x112912230>, 1690563968.225089, <multiprocessing.synchronize.Event object at 0x112910b80>, <multiprocessing.connection.Connection object at 0x112910ee0>)
2023-07-28 13:06:14.353 | INFO     | __mp_main__:write_events:319 - event_type='window' starting
Unhandled exception in listener callback
Traceback (most recent call last):
  File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/pynput/_util/__init__.py", line 230, in inner
    return f(self, *args, **kwargs)
  File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/pynput/_util/darwin.py", line 286, in _handler
    self._handle(proxy, event_type, event, refcon, is_injected)
  File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/pynput/keyboard/_darwin.py", line 291, in _handle
    self.on_press(self._SPECIAL_KEYS[key])
  File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/pynput/_util/__init__.py", line 146, in inner
    if f(*args) is False:
TypeError: read_keyboard_events.<locals>.on_press() missing 1 required positional argument: 'injected'
^C2023-07-28 13:06:23.727 | INFO     | __mp_main__:write_events:348 - event_type='screen' done
2023-07-28 13:06:23.728 | INFO     | __mp_main__:wrapper_logging:126 -  <- Leave: write_events(None)
2023-07-28 13:06:23.842 | INFO     | __mp_main__:write_events:348 - event_type='action' done
2023-07-28 13:06:23.842 | INFO     | __mp_main__:write_events:348 - event_type='window' done
2023-07-28 13:06:23.843 | INFO     | __mp_main__:wrapper_logging:126 -  <- Leave: write_events(None)
2023-07-28 13:06:23.843 | INFO     | __mp_main__:wrapper_logging:126 -  <- Leave: write_events(None)
2023-07-28 13:06:23.848 | INFO     | __main__:read_screen_events:518 - Done
2023-07-28 13:06:23.855 | INFO     | __main__:process_events:239 - Done
2023-07-28 13:06:23.857 | INFO     | __main__:wrapper_logging:126 -  <- Leave: process_events(None)
2023-07-28 13:06:24.192 | INFO     | __main__:log_memory_usage:70 - source='File "/Users/d/OpenAdapt/openadapt/window/_macos.py", line 213'
2023-07-28 13:06:24.193 | INFO     | __main__:log_memory_usage:71 - 	new_KiB=29253.9501953125 total_KiB=29253.9501953125 new_blocks=18271 total_blocks=18271
2023-07-28 13:06:24.195 | INFO     | __main__:log_memory_usage:70 - source='File "/Users/d/OpenAdapt/.venv/lib/python3.10/site-packages/mss/darwin.py", line 226'
2023-07-28 13:06:24.196 | INFO     | __main__:log_memory_usage:71 - 	new_KiB=20250.0556640625 total_KiB=20250.0556640625 new_blocks=2 total_blocks=2
2023-07-28 13:06:24.197 | INFO     | __main__:log_memory_usage:70 - source='File "/Users/d/OpenAdapt/openadapt/window/_macos.py", line 50'
2023-07-28 13:06:24.197 | INFO     | __main__:log_memory_usage:71 - 	new_KiB=14095.83203125 total_KiB=14095.83203125 new_blocks=485 total_blocks=485
2023-07-28 13:06:24.455 | INFO     | __main__:wrapper_logging:126 -  <- Leave: read_window_events(None)
2023-07-28 13:06:32.162 | INFO     | __main__:log_memory_usage:74 - trace_str=
                      types |   # objects |   total size
=========================== | =========== | ============
                        str |       21855 |     42.84 MB
                      tuple |       88730 |      6.04 MB
                       dict |        8355 |      2.30 MB
                       list |       14780 |      2.01 MB
        objc.pyobjc_unicode |         124 |    246.59 KB
                        int |        5703 |    156.58 KB
  tracemalloc.StatisticDiff |        2065 |    145.20 KB
      tracemalloc.Traceback |        2065 |     96.80 KB
          collections.deque |         147 |     89.58 KB
                       type |          53 |     67.13 KB
                        set |         174 |     47.45 KB
                       code |         191 |     40.73 KB
                    weakref |         413 |     29.04 KB
                  frozenset |          87 |     24.10 KB
       objc.objc_meta_class |          13 |     13.61 KB
2023-07-28 13:06:32.164 | INFO     | __main__:record:965 - joining...
2023-07-28 13:06:32.165 | INFO     | __mp_main__:performance_stats_writer:597 - Performance stats writer done
2023-07-28 13:06:32.165 | INFO     | __mp_main__:wrapper_logging:126 -  <- Leave: performance_stats_writer(None)
2023-07-28 13:06:32.174 | INFO     | __mp_main__:memory_writer:644 - Memory writer done
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
2023-07-28 13:06:32.802 | INFO     | openadapt.utils:plot_performance:706 - fpath='performance/performance-1690563968.225089.png'
2023-07-28 13:06:33.381 | INFO     | __main__:record:980 - Saved recording_timestamp=1690563968.225089
2023-07-28 13:06:33.383 | INFO     | __main__:wrapper_logging:126 -  <- Leave: record(None)```
2. I'm on Ventura 13.4

**Comment by ayewo** [comment]
@dianzrong 

Thanks. 

1. Is the chip Intel or Apple Silicon?
2. Are you by chance using an external keyboard?

**Comment by dianzrong** [comment]
@ayewo 

1. Apple silicon (M1)
2. Not an external keyboard

**Comment by ayewo** [comment]
@dianzrong got it.

Currently on macOS 12.6 but I plan to update to Ventura 13.5 soon. 
Hopefully I'll take a look again when I'm also on Ventura.

**Comment by abrichr** [comment]
Closing as part of architecture transition. Legacy frozen at v0.46.0. See PR #960.
