### ISSUE TITLE
Investigate Python 3.11

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#370]
### Describe the bug

```
(openadapt-py3.11) C:\Users\erika\OpenAdapt>python -m openadapt.visualize
2023-07-08 18:52:36.862 | INFO     | openadapt.config:<module>:160 - STOP_STRS=['oa.stop']
2023-07-08 18:52:36.862 | INFO     | openadapt.config:<module>:160 - SPECIAL_CHAR_STOP_SEQUENCES=[['ctrl', 'ctrl', 'ctrl']]
2023-07-08 18:52:36.862 | INFO     | openadapt.config:<module>:160 - STOP_SEQUENCES=[['o', 'a', '.', 's', 't', 'o', 'p'], ['ctrl', 'ctrl', 'ctrl']]
2023-07-08 18:52:36.876 | INFO     | openadapt.config:<module>:160 - CACHE_DIR_PATH=.cache
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - CACHE_ENABLED=True
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - CACHE_VERBOSITY=0
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - DB_ECHO=False
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - DB_FNAME=openadapt.db
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - OPENAI_API_KEY=<set your api key in .env>
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - OPENAI_MODEL_NAME=gpt-3.5-turbo
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - RECORD_READ_ACTIVE_ELEMENT_STATE=False
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - REPLAY_STRIP_ELEMENT_STATE=True
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - IGNORE_WARNINGS=False
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - ACTION_TEXT_SEP=-
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - ACTION_TEXT_NAME_PREFIX=<
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - ACTION_TEXT_NAME_SUFFIX=>
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - SCRUB_ENABLED=True
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - SCRUB_CHAR=*
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - SCRUB_LANGUAGE=en
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - SCRUB_FILL_COLOR=255
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - SCRUB_CONFIG_TRF={'nlp_engine_name': 'spacy', 'models': [{'lang_code': 'en', 'model_name': 'en_core_web_trf'}]}
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - SCRUB_IGNORE_ENTITIES=['DATE_TIME', 'URL']
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - SCRUB_KEYS_HTML=['text', 'canonical_text', 'title', 'state', 'task_description', 'key_char', 'canonical_key_char', 'key_vk', 'children']
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - PLOT_PERFORMANCE=True
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - ROOT_DIRPATH=C:\Users\erika\OpenAdapt
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - DB_FPATH=C:\Users\erika\OpenAdapt\openadapt.db
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - DB_URL=sqlite:///C:\Users\erika\OpenAdapt\openadapt.db
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - DT_FMT=%Y-%m-%d_%H-%M-%S
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - DIRNAME_PERFORMANCE_PLOTS=performance
2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - ZIPPED_RECORDING_FOLDER_PATH=C:\Users\erika\OpenAdapt\data\zipped2023-07-08 18:52:36.878 | INFO     | openadapt.config:<module>:160 - ENV_FILE_PATH=C:\Users\erika\OpenAdapt\.env
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\erika\OpenAdapt\openadapt\visualize.py", line 33, in <module>
    from openadapt import scrub
  File "C:\Users\erika\OpenAdapt\openadapt\scrub.py", line 14, in <module>
    from presidio_analyzer import AnalyzerEngine
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\presidio_analyzer\__init__.py", line 9, in <module>
    from presidio_analyzer.entity_recognizer import EntityRecognizer
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\presidio_analyzer\entity_recognizer.py", line 6, in <module>
    from presidio_analyzer.nlp_engine import NlpArtifacts
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\presidio_analyzer\nlp_engine\__init__.py", line 3, in <module>
    from .nlp_artifacts import NlpArtifacts
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\presidio_analyzer\nlp_engine\nlp_artifacts.py", line 4, in <module>
    from spacy.tokens import Doc, Span
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\spacy\__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\spacy\pipeline\attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy\pipeline\pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\spacy\tokens\__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy\tokens\doc.pyx", line 36, in init spacy.tokens.doc
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\spacy\schemas.py", line 158, in <module>
    class TokenPatternString(BaseModel):
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\pydantic\main.py", line 326, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\pydantic\utils.py", line 225, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\erika\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2722, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'in' is not a valid parameter name
```

### To Reproduce

Python 3.11 Windows:

```
python -m openadapt.visualize
```

**Comment by KrishPatel13** [comment]
Presidio support 3.7 >= python version. So we do not think so it is related to that!

https://microsoft.github.io/presidio/installation/

Need to investigate more!

**Comment by KrishPatel13** [comment]
Some related discussion: https://github.com/tiangolo/fastapi/issues/5048

**Comment by KrishPatel13** [comment]
We could also rename this to Investigate 3.11 and then list down the conflicting libraries that do now work with 3.11 for this issue

**Comment by abrichr** [comment]
Closing as part of architecture transition. Legacy frozen at v0.46.0. See PR #960.
