### ISSUE TITLE
[Bug]: exception when using stop sequence on python3.11

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#371]
### Describe the bug

```
2023-07-08 18:56:50.138 | INFO     | __mp_main__:performance_stats_writer:518 - performance stats writer starting
2023-07-08 18:56:52.262 | INFO     | __main__:read_window_events:487 - _window_data={'title': '314474203/19600', 'left': -9, 'top': -9, 'width': 1938, 'height': 1038, 'window_id': 0}
2023-07-08 18:57:03.823 | WARNING  | openadapt.window._windows:get_active_window_state:31 - No Windows of that application are active
2023-07-08 18:57:09.351 | WARNING  | openadapt.window._windows:get_active_window_state:31 - No Windows of that application are active
2023-07-08 18:57:20.691 | INFO     | __main__:on_press:646 - Stop sequence entered! Stopping recording now.
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\pynput\_util\__init__.py", line 230, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\pynput\keyboard\_win32.py", line 299, in _process
    self.on_press(key, injected)
  File "C:\Users\erika\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-CpCf7oPf-py3.11\Lib\site-packages\pynput\_util\__init__.py", line 146, in inner
    if f(*args) is False:
       ^^^^^^^^
  File "C:\Users\erika\OpenAdapt\openadapt\record.py", line 630, in on_press
    keyboard.KeyCode.from_char(stop_sequence[stop_sequence_indices[i]])
                               ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2023-07-08 18:57:20.832 | INFO     | __mp_main__:write_events:319 - event_type='window' done
2023-07-08 18:57:20.832 | INFO     | __mp_main__:wrapper_logging:99 -  <- Leave: write_events(None)
2023-07-08 18:57:20.853 | INFO     | __mp_main__:write_events:319 - event_type='action' done
2023-07-08 18:57:20.858 | INFO     | __mp_main__:wrapper_logging:99 -  <- Leave: write_events(None)
2023-07-08 18:57:20.791 | INFO     | __main__:read_screen_events:448 - done
2023-07-08 18:57:20.799 | INFO     | __main__:process_events:194 - done
```

### To Reproduce

```
python -m openadapt.record foo
```

**Comment by angelala3252** [comment]
@abrichr I'm unable to recreate this bug. What are the exact steps taken after starting the recording?

**Comment by ulysseskan** [comment]
I wasn't able to repro this either, but from the error, it looks like there's a problem with `stop_sequence_indices[i]` exceeding the length of the `STOP_SEQUENCES` list.  

One way to handle this might be to update the loop on line 624 of record.py as follows:

```
        if stop_sequence_indices[i] >= len(stop_sequence):
            # Reset index if it exceeds the length of sequence
            stop_sequence_indices[i] = 0
...
```

I'm not familiar with this codebase though so I'm not sure what side effects, if any, this may have.

**Comment by abrichr** [comment]
Closing as part of architecture transition. Legacy frozen at v0.46.0. See PR #960.
