### ISSUE TITLE
[Bug]: visualize.py TypeError: expected string

### ISSUE THREAD

**Issue by AvidEslami** [OpenAdaptAI/OpenAdapt#400]
### Describe the bug

2023-07-18 12:16:42.117 | INFO     | __main__:main:191 - len(action_events)=8
Preparing HTML:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 6/8 [00:02<00:00,  2.83event/s] 
2023-07-18 12:16:44.372 | ERROR    | __main__:<module>:294 - An error has been caught in function '<module>', process 'MainProcess' (16944), thread 'MainThread' (12428):
Traceback (most recent call last):

> File "C:\Users\avide\OneDrive\Desktop\Coding Proj\MLDSAI\puterbot\openadapt\visualize.py", line 294, in <module>
    main()
    -> <function main at 0x00000221F5AEAA70>

  File "C:\Users\avide\OneDrive\Desktop\Coding Proj\MLDSAI\puterbot\openadapt\visualize.py", line 208, in main
    image = display_event(action_event)
            |             -> ActionEvent(id=1047, name='type', timestamp=1689765713.4416907, recording_timestamp=1689696951.3192976, screenshot_timestamp=...
            -> <function display_event at 0x00000221DE435480>

  File "c:\users\avide\onedrive\desktop\coding proj\mldsai\puterbot\openadapt\utils.py", line 372, in display_event
    image = draw_text(x, y, text, image, outline=True)
            |         |  |  |     -> <PIL.Image.Image image mode=RGBA size=1920x1080 at 0x221F6CA38B0>
            |         |  |  -> None
            |         |  -> 540.0
            |         -> 960.0
            -> <function draw_text at 0x00000221DE4352D0>

  File "c:\users\avide\onedrive\desktop\coding proj\mldsai\puterbot\openadapt\utils.py", line 248, in draw_text
    text_bbox = font.getbbox(text)
                |    |       -> None
                |    -> <function FreeTypeFont.getbbox at 0x00000221DD6CBF40>
                -> <PIL.ImageFont.FreeTypeFont object at 0x00000221F6CA2CB0>

  File "C:\Users\avide\OneDrive\Desktop\Coding Proj\MLDSAI\puterbot\.venv10\lib\site-packages\PIL\ImageFont.py", line 408, in getbbox
    size, offset = self.font.getsize(
                   |    |    -> <method 'getsize' of 'Font' objects>
                   |    -> <Font object at 0x00000221F6D18030>
                   -> <PIL.ImageFont.FreeTypeFont object at 0x00000221F6CA2CB0>

TypeError: expected string

### To Reproduce

I use Windows, the following command gave this error:
```
py .\openadapt\visualize.py
```

**Comment by KrishPatel13** [comment]
I had experienced the same error initiated here: https://github.com/OpenAdaptAI/OpenAdapt/issues/210

**Comment by AvidEslami** [comment]
Closed since duplicate of #210
