### ISSUE TITLE
[Bug]: Recording Events are Sometimes Received in an Incorrect Order

### ISSUE THREAD

**Issue by AvidEslami** [OpenAdaptAI/OpenAdapt#445]
### Describe the bug

```
Exception in thread Thread-8 (process_events):
Traceback (most recent call last):
  File "C:\Users\avide\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\avide\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\avide\OneDrive\Desktop\Coding Proj\MLDSAI\NewFork\OpenAdapt\openadapt\record.py", line 128, in wrapper_logging
    result = func(*args, **kwargs)
  File "C:\Users\avide\OneDrive\Desktop\Coding Proj\MLDSAI\NewFork\OpenAdapt\openadapt\record.py", line 201, in process_events
    assert event.timestamp > prev_event.timestamp, (
AssertionError: (Event(timestamp=1691419957.6369324, type='screen', data=<ScreenShot pos=0,0 size=1920x1080>), Event(timestamp=1691419957.6373177, type='file', data={}))
```
```
        if prev_event is not None:
            assert event.timestamp > prev_event.timestamp, (event, prev_event)
```
The assertion above sometimes fails due to a race condition where events are received in the incorrect order, this seems to occur more often when the computational load on the device is high
 - Solution most likely involves sorting the incoming events by timestamp

### To Reproduce

```
python .\openadapt\record.py TestReplay
```
I'm not aware of any ways to guarantee this bug, but having the computer busy with other tasks could help

**Comment by abrichr** [comment]
Closing as part of architecture transition to modular packages. Legacy codebase frozen at v0.46.0. See PR #960.
