### ISSUE TITLE
Bug: Long Recordings

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#45]
```
2023-04-30 18:57:43.832 | INFO     | __mp_main__:write_events:230 - event_type='screen' starting
2023-04-30 18:57:43.832 | INFO     | __mp_main__:write_events:230 - event_type='window' starting
2023-04-30 18:57:43.833 | INFO     | __mp_main__:write_events:230 - event_type='input' starting
^C2023-04-30 19:00:57.042 | INFO     | __mp_main__:write_events:239 - event_type='window' done
2023-04-30 19:00:57.042 | INFO     | __main__:record:679 - joining...
2023-04-30 19:00:57.043 | INFO     | __main__:read_screen_events:367 - done
2023-04-30 19:00:57.043 | INFO     | __mp_main__:write_events:239 - event_type='input' done
2023-04-30 19:00:57.044 | INFO     | __main__:process_events:145 - done


```

<CTRL+C>:
```
2023-04-30 19:02:45.690 | INFO     | __mp_main__:write_events:239 - event_type='screen' done
^CTraceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/record.py", line 695, in <module>
    fire.Fire(record)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/record.py", line 685, in record
    screen_event_writer.join()
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
^CException ignored in atexit callback: <function _exit_function at 0x13479b6d0>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt: 
```

**Comment by dianzrong** [comment]
I'm unable to replicate this output above as I get 8 lines before the "write_events" lines. See the output below:
```
2023-05-12 21:46:06.750 | INFO     | __main__:record:581 - task_description='testing out puterbot'
2023-05-12 21:46:06.790 | INFO     | __main__:create_recording:518 - recording=Recording(id=47, timestamp=1683942366.750409, monitor_width=1440, monitor_height=900, double_click_interval_seconds=0.5, double_click_distance_pixels=5, platform='darwin', task_description='testing out puterbot')
2023-05-12 21:46:06.803 | INFO     | __main__:read_window_events:386 - starting
2023-05-12 21:46:06.807 | INFO     | __main__:read_screen_events:360 - starting
2023-05-12 21:46:06.814 | INFO     | __main__:process_events:91 - starting
2023-05-12 21:46:06.836 | INFO     | __main__:read_window_events:416 - title='Terminal puterbot — Python -m puterbot.record testing out puterbot — 80×24' prev_title=None geometry=(764.0, 483.0, 570.0, 371.0) prev_geometry=None
2023-05-12 21:46:06.900 | WARNING  | __main__:read_window_events:398 - geometry=None
2023-05-12 21:46:06.902 | INFO     | __main__:read_window_events:416 - title='Terminal puterbot — Python ◂ Python -m puterbot.record testing out puterbot — 80×24' prev_title='Terminal puterbot — Python -m puterbot.record testing out puterbot — 80×24' geometry=(764.0, 483.0, 570.0, 371.0) prev_geometry=(764.0, 483.0, 570.0, 371.0)
2023-05-12 21:46:08.315 | INFO     | __mp_main__:write_events:230 - event_type='window' starting
2023-05-12 21:46:08.323 | INFO     | __mp_main__:write_events:230 - event_type='action' starting
2023-05-12 21:46:08.325 | INFO     | __mp_main__:write_events:230 - event_type='screen' starting
^C2023-05-12 21:49:06.177 | INFO     | __main__:record:679 - joining...
2023-05-12 21:49:06.177 | INFO     | __mp_main__:write_events:239 - event_type='window' done
2023-05-12 21:49:06.177 | INFO     | __mp_main__:write_events:239 - event_type='action' done
2023-05-12 21:49:06.179 | INFO     | __main__:read_screen_events:367 - done
2023-05-12 21:49:06.180 | INFO     | __main__:process_events:145 - done
2023-05-12 21:49:07.083 | INFO     | __mp_main__:write_events:239 - event_type='screen' done
2023-05-12 21:49:07.170 | INFO     | __main__:record:691 - done 
```
Similarly, I don't get a bug after the input.
Has this bug been fixed?
