### ISSUE TITLE
[Bug]: Unknown encoding cl100k_base

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#677]
### Describe the bug

Reported by trapperjon1980 on Discord:

```
Last login: Fri May 17 06:10:40 on ttys001
cd /private/var/folders/5m/0w_pgsmn70s6n6pkfrfknw2m0000gn/T/AppTranslocation/8C8BCD24-4DBD-45BC-B333-1B938FC59DB9/d/OpenAdapt-2.app/Contents/MacOS && ./OpenAdapt.app; exit;
(base) jonathankotthoff@Jonathans-Laptop ~ % cd /private/var/folders/5m/0w_pgsmn70s6n6pkfrfknw2m0000gn/T/AppTranslocation/8C8BCD24-4DBD-45BC-B333-1B938FC59DB9/d/OpenAdapt-2.app/Contents/MacOS && ./OpenAdapt.app; exit;
Traceback (most recent call last):
  File "openadapt/entrypoint.py", line 11, in <module>
    from openadapt.app import tray
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "openadapt/app/tray.py", line 46, in <module>
    from openadapt.strategies.base import BaseReplayStrategy
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "openadapt/strategies/__init__.py", line 12, in <module>
    from openadapt.strategies.stateful import StatefulReplayStrategy
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "openadapt/strategies/stateful.py", line 15, in <module>
    from openadapt.strategies.mixins.openai import OpenAIReplayStrategyMixin
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "openadapt/strategies/mixins/openai.py", line 33, in <module>
    encoding = tiktoken.get_encoding("cl100k_base")
  File "tiktoken/registry.py", line 60, in get_encoding
ValueError: Unknown encoding cl100k_base
[52523] Failed to execute script 'entrypoint' due to unhandled exception: Unknown encoding cl100k_base
[52523] Traceback:
Traceback (most recent call last):
  File "openadapt/entrypoint.py", line 11, in <module>
    from openadapt.app import tray
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "openadapt/app/tray.py", line 46, in <module>
    from openadapt.strategies.base import BaseReplayStrategy
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "openadapt/strategies/__init__.py", line 12, in <module>
    from openadapt.strategies.stateful import StatefulReplayStrategy
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "openadapt/strategies/stateful.py", line 15, in <module>
    from openadapt.strategies.mixins.openai import OpenAIReplayStrategyMixin
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "openadapt/strategies/mixins/openai.py", line 33, in <module>
    encoding = tiktoken.get_encoding("cl100k_base")
  File "tiktoken/registry.py", line 60, in get_encoding
ValueError: Unknown encoding cl100k_base


Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

```

### To Reproduce

See description

**Comment by abrichr** [comment]
Relevant: https://github.com/openai/tiktoken/issues/80#issuecomment-1484965176
