### ISSUE TITLE
[Bug]: Anthropic adapter logging issue

### ISSUE THREAD

**Issue by Sukrit5** [OpenAdaptAI/OpenAdapt#716]
### Describe the bug

When running the command `python -m openadapt.replay VisualReplayStrategy --instructions "multiply 8x9"`, I run into the following issue
`--- Logging error in Loguru Handler #1 ---
Record was: None
Traceback (most recent call last):
  File "/Users/.../miniconda3/envs/p1/lib/python3.10/site-packages/loguru/_handler.py", line 272, in _queued_writer
    message = queue.get()
  File "/Users/.../miniconda3/envs/p1/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'
--- End of logging error ---`

The issue seems to be related to the serialization and de serialization of the record. Related post here https://github.com/Delgan/loguru/issues/329, though I'm not sure why this happens when running an anthropic adapter, and not an openai adapter

### To Reproduce

I use macOS
Set the adapter to anthropic, and then follow the same procedure as this twitter demo: https://x.com/abrichr/status/1784307190062342237

**Comment by abrichr** [comment]
Closing as part of the architecture transition to modular packages. The legacy codebase has been frozen at v0.46.0.

This Anthropic adapter logging bug was in the legacy adapter which has been replaced.

For the new modular architecture, please open issues in the relevant package repository:
- GUI capture: https://github.com/OpenAdaptAI/openadapt-capture
- ML/training: https://github.com/OpenAdaptAI/openadapt-ml
- Benchmarks: https://github.com/OpenAdaptAI/openadapt-evals
- Privacy: https://github.com/OpenAdaptAI/openadapt-privacy

See PR #960 for details on the new architecture.
