### ISSUE TITLE
Support multiple monitors

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#766]
### Feature request

We would like to support multiple monitors.

User @Alphadev on Discord reports no screenshots in `python -m openadapt.visualize` on https://github.com/OpenAdaptAI/OpenAdapt/pull/763:

![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/d06f64fb-4171-4b99-ac7f-ed2b216d2437)

This involves identifying where support needs to be added. e.g.:
- https://github.com/OpenAdaptAI/OpenAdapt/blob/835bb171bc89bccf67397515ff5eb0b257c528bd/openadapt/utils.py#L421

### Motivation

https://github.com/OpenAdaptAI/OpenAdapt/issues/583

We would like to support configurations as similar as possible to a typical office worker's machine.

**Comment by Amanullah1002** [comment]
/attempt #766 I will alter the method to support multiple monitors of different width and heights.

**Comment by abrichr** [comment]
Please note this involves:
- Running `python -m openadapt.visualize` and taking some screenshots of the visualization containing more than one monitor, and submitting these with your PR
- Implement one or more tests

**Comment by abhishek818** [comment]
@abrichr can you help with the below error:
```
(.venv) gitpod /workspace/OpenAdapt (main) $ python -m openadapt.record "testing out openadapt"
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.10.12/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gitpod/.pyenv/versions/3.10.12/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/OpenAdapt/openadapt/record.py", line 28, in <module>
    from openadapt.models import Recording
  File "/workspace/OpenAdapt/openadapt/models.py", line 16, in <module>
    from openadapt import window
  File "/workspace/OpenAdapt/openadapt/window/__init__.py", line 17, in <module>
    from . import _windows as impl
  File "/workspace/OpenAdapt/openadapt/window/_windows.py", line 55, in <module>
    active_window: pywinauto.application.WindowSpecification,
AttributeError: module 'pywinauto' has no attribute 'application'
```

**Comment by abrichr** [comment]
Hi @abhishek818 , thank you for reporting this error! Can you please post the output of `git status`?

I haven't seen this one, but I don't use Windows. @KIRA009 any suggestions? 🙏

**Comment by abhishek818** [comment]
@abrichr I have no changes done, I was trying to get started and setup openadapt first. I mean `git status` is empty.

**Comment by abhishek818** [comment]
alrighty, seems the issue is with my use of gitpod instance (linux based) on a windows machine. (I use gitpod for code development)

**Comment by onyedikachi-david** [comment]
@abrichr 
![Screenshot 2024-06-18 at 12 07 22](https://github.com/OpenAdaptAI/OpenAdapt/assets/51977119/c546cf2d-e3c1-4310-9a4c-2e39a3045ed9)

I get this error: 
```console
sqlite3.OperationalError: no such column: recording.original_recording_id` when i run: `python -m openadapt.app.visualize
```

this error also: 

```console
File "/Users/onyedikachi/Library/Caches/pypoetry/virtualenvs/openadapt-hlnjL-LM-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 789, in reflect_table
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: input_even,
``` 

when i run: 
```console
cd openadapt && alembic upgrade head && cd ..
```

**Comment by onyedikachi-david** [comment]
Yes @KIRA009

**Comment by onyedikachi-david** [comment]
Yes I followed the steps, I'll drop the database and give you feedback.

**Comment by onyedikachi-david** [comment]
![Alembic error](https://github.com/OpenAdaptAI/OpenAdapt/assets/51977119/5960c34f-fa4b-4c1d-b49b-c861aa3022b7)
The error still persist... Was a migration file deleted?

**Comment by onyedikachi-david** [comment]
@KIRA009  This is the commit I am on: `git log -1`

```console
commit 835bb171bc89bccf67397515ff5eb0b257c528bd (HEAD -> main, tag: v0.33.2, origin/main, origin/HEAD)
Author: OpenAdapt Bot <bot@openadapt.ai>
Date:   Sat Jun 15 16:01:14 2024 +0000

    0.33.2
    
    Automatically generated by python-semantic-release
```

**Comment by abrichr** [comment]
I suggest a fresh `git clone`. Please try following the manual setup instructions exactly: https://github.com/OpenAdaptAI/OpenAdapt?tab=readme-ov-file#manual-setup

**Comment by onyedikachi-david** [comment]
Thank you @abrichr, just did that and more: deleted poetry cache, venv. Yet the error somehow still shows up. :)

**Comment by onyedikachi-david** [comment]
just did a workaround. @abrichr

**Comment by abrichr** [comment]
@onyedikachi-david what was the workaround?

**Comment by onyedikachi-david** [comment]
> @onyedikachi-david what was the workaround?

I initially tried tracing the migration file that was causing the error by downloading(see screen shot) the alembic versions folder of each repo  version tag that added db migrations, namely; v0.60, v0.16.1...; I noticed that at v0.26.0, up to 5 migration version were pushed, and that was where the error started, other versions did not error, when i ran `alembic upgrade head`. Not wanting to go through all the 5 db migrations, I decided to generate an SQL query from the models.py file, ran the query to create the db and that was it. I was now able to run `python -m openadapt.app.dashboard.run` command and others without the missing db column error.

**Comment by abrichr** [comment]
Closing as part of the architecture transition to modular packages. The legacy codebase has been frozen at v0.46.0.

Multiple monitor support would be implemented in the new openadapt-capture package.

For the new modular architecture, please open issues in the relevant package repository:
- GUI capture: https://github.com/OpenAdaptAI/openadapt-capture
- ML/training: https://github.com/OpenAdaptAI/openadapt-ml
- Benchmarks: https://github.com/OpenAdaptAI/openadapt-evals
- Privacy: https://github.com/OpenAdaptAI/openadapt-privacy

See PR #960 for details on the new architecture.
