### ISSUE TITLE
[Bug]: alembic command not working

### ISSUE THREAD

**Issue by absha03** [OpenAdaptAI/OpenAdapt#800]
### Describe the bug

at the last setup command, I get this alembic error:

(openadapt-py3.10) PS C:\Users\abhis\openAdapt\OpenAdapt\openadapt> alembic upgrade head

Traceback (most recent call last):
File "C:\Users\abhis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return run_code(code, main_globals, None,
File "C:\Users\abhis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\Scripts\alembic.exe_main.py", line 7, in
File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\alembic\config.py", line 590, in main
CommandLine(prog=prog).main(argv=argv)
File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\alembic\config.py", line 584, in main
self.run_cmd(cfg, options)
File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\alembic\config.py", line 561, in run_cmd
fn(
File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\alembic\command.py", line 322, in upgrade
script.run_env()
File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\alembic\script\base.py", line 569, in run_env
util.load_python_file(self.dir, "env.py")
File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\alembic\util\pyfiles.py", line 94, in load_python_file
module = load_module_py(module_id, path)
File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\alembic\util\pyfiles.py", line 110, in load_module_py
spec.loader.exec_module(module) # type: ignore
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\alembic\env.py", line 12, in
from openadapt.db import db
File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\db_init.py", line 3, in
from .db import export_recording # noqa: F401
File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\db\db.py", line 77, in
Base = get_base(engine)
File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\db\db.py", line 68, in get_base
Base = declarative_base(
File "", line 2, in declarative_base
File "c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages\sqlalchemy\util\deprecations.py", line 386, in warned
return fn(*args, **kwargs) # type: ignore[no-any-return]
File "c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages\sqlalchemy\ext\declarative_init.py", line 27, in declarative_base
return _declarative_base(*arg, **kw)

TypeError: declarative_base() got an unexpected keyword argument 'bind'

### To Reproduce

on windows 11 on PowerShell 7: (openadapt-py3.10) PS C:\Users\abhis\openAdapt\OpenAdapt\openadapt> alembic upgrade head

**Comment by abrichr** [comment]
Thanks for reporting this @absha03 . It seems you may not be on the correct version of `alembic`. Can you please `poetry install` before running this command? Make sure to follow the instructions in https://github.com/OpenAdaptAI/OpenAdapt?tab=readme-ov-file#manual-setup

**Comment by abrichr** [comment]
Closing as part of the architecture transition to modular packages. The legacy codebase has been frozen at v0.46.0.

Alembic command issues were in the legacy database migration system which has been redesigned.

For the new modular architecture, please open issues in the relevant package repository:
- GUI capture: https://github.com/OpenAdaptAI/openadapt-capture
- ML/training: https://github.com/OpenAdaptAI/openadapt-ml
- Benchmarks: https://github.com/OpenAdaptAI/openadapt-evals
- Privacy: https://github.com/OpenAdaptAI/openadapt-privacy

See PR #960 for details on the new architecture.
