### ISSUE TITLE
[Bug]: Failed to execute script 'entrypoint' due to unhandled exception: 'NoneType' has no attribute 'write'

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#815]
### Describe the bug

After stopping a recording on Windows executable via stop sequence, the following error is displayed:

![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/cb4e0df1-139c-41c4-82b5-e8a152a19464)

```
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "openadapt\record.py", line 1081, in record_audio
    model = whisper.load_model("base")
  File "whisper\__init__.py", line 133, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
  File "whisper\__init__.py", line 70, in _download
    with tqdm(
  File "tqdm\std.py", line 1109, in __init__
  File "tqdm\std.py", line 1361, in refresh
  File "tqdm\std.py", line 1509, in display
  File "tqdm\std.py", line 350, in print_status
  File "tqdm\std.py", line 343, in fp_write
  File "tqdm\utils.py", line 89, in __getattr__
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "openadapt\entrypoint.py", line 7, in <module>
    multiprocessing.freeze_support()
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'
```

### To Reproduce

Download and run executable, start a recording, then stop it.

**Comment by abrichr** [comment]
Related: https://www.eatdirtshit.rocks/sittin-on-a-rainbow-using-buzz-to-transcribe-speech/

**Comment by abrichr** [comment]
Possibly related: https://www.eatdirtshit.rocks/sittin-on-a-rainbow-using-buzz-to-transcribe-speech/

As a workaround we should add `RECORD_AUDIO` to the dashboard config and default to `False`.

**Comment by KIRA009** [comment]
@abrichr I checked this out with the latest build on windows on a fresh install, and didn't face this issue. Since we are bundling the whisper 'base' model with the build, I don't think we should be  Could you try it one more time and let me know if you still find this, we can disable audio recording in that case.

**Comment by abrichr** [comment]
@KIRA009 it does not appear to be consistent. Let's disable audio recording by default, and also add it to the dashboard configuration.

**Comment by KIRA009** [comment]
PR: https://github.com/OpenAdaptAI/OpenAdapt/pull/826
