### ISSUE TITLE
[Bug]: Vanilla replay strategy fails with below error

### ISSUE THREAD

**Issue by absha03** [OpenAdaptAI/OpenAdapt#859]
### Describe the bug

PS C:\Users\abhis\openAdapt\OpenAdapt> poetry shell
Spawning shell within C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10
PowerShell 7.4.3
(openadapt-py3.10) PS C:\Users\abhis\openAdapt\OpenAdapt> python -m openadapt.replay VanillaReplayStrategy --instructions "calculate 9-8"
[2024-07-18 00:09:23.481] [recordLogger] [info] Created d3d11 device from 0
[2024-07-18 00:09:23.482] [recordLogger] [info] found 1 displays
Traceback (most recent call last):
  File "C:\Users\abhis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abhis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\replay.py", line 19, in <module>
    from openadapt import capture as _capture, utils
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\utils.py", line 50, in <module>
    from openadapt.models import ActionEvent
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\models.py", line 16, in <module>
    from openadapt import window
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\window\__init__.py", line 17, in <module>
    from . import _windows as impl
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\window\_windows.py", line 6, in <module>
    import pywinauto
  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\pywinauto\__init__.py", line 87, in <module>
    from .sysinfo import UIA_support
  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\pywinauto\sysinfo.py", line 44, in <module>
    import comtypes  # noqa: E402
  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\comtypes\__init__.py", line 191, in <module>
    CoInitializeEx()
  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\comtypes\__init__.py", line 181, in CoInitializeEx
    _ole32.CoInitializeEx(None, flags)
  File "_ctypes/callproc.c", line 993, in GetResult
OSError: [WinError -2147417850] Cannot change thread mode after it is set

### To Reproduce

on win PowerShell 7 follow steps as mentioned

**Comment by abrichr** [comment]
Thank you @absha03 ! Can you please clarify whether this also happens with other strategies, e.g. `NaiveReplayStrategy`?

**Comment by absha03** [comment]
yes as seen below: (openadapt-py3.10) PS C:\Users\abhis\openAdapt\OpenAdapt> python -m openadapt.replay NaiveReplayStrategy --instructions "calculate 9-8"
[2024-07-18 22:38:32.963] [recordLogger] [info] Created d3d11 device from 0
[2024-07-18 22:38:32.964] [recordLogger] [info] found 1 displays
Traceback (most recent call last):
  File "C:\Users\abhis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abhis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\replay.py", line 19, in <module>
    from openadapt import capture as _capture, utils
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\utils.py", line 50, in <module>
    from openadapt.models import ActionEvent
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\models.py", line 16, in <module>
    from openadapt import window
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\window\__init__.py", line 17, in <module>
    from . import _windows as impl
  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\window\_windows.py", line 6, in <module>
    import pywinauto
  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\pywinauto\__init__.py", line 87, in <module>
    from .sysinfo import UIA_support
  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\pywinauto\sysinfo.py", line 44, in <module>
    import comtypes  # noqa: E402
  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\comtypes\__init__.py", line 191, in <module>
    CoInitializeEx()
  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\comtypes\__init__.py", line 181, in CoInitializeEx
    _ole32.CoInitializeEx(None, flags)
  File "_ctypes/callproc.c", line 993, in GetResult
OSError: [WinError -2147417850] Cannot change thread mode after it is set

**Comment by abrichr** [comment]
Closing as part of the architecture transition to modular packages. The legacy codebase has been frozen at v0.46.0.

This Vanilla replay strategy bug was in the legacy replay system which has been replaced.

For the new modular architecture, please open issues in the relevant package repository:
- GUI capture: https://github.com/OpenAdaptAI/openadapt-capture
- ML/training: https://github.com/OpenAdaptAI/openadapt-ml
- Benchmarks: https://github.com/OpenAdaptAI/openadapt-evals
- Privacy: https://github.com/OpenAdaptAI/openadapt-privacy

See PR #960 for details on the new architecture.
