### ISSUE TITLE
[Bug]: App broken

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#901]
### Describe the bug

Reported by @limaconnect on Discord:

```
Fault bucket 1886883604746232999, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: OpenAdapt.exe
P2: 0.0.0.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\?\C:\Users\p8tty\AppData\Local\Temp\RDR68C6.tmp\empty.txt
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7409c011-1509-42cd-9a1a-a2f9310c4d51.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20240808_1_EC_0_inject.etl
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e430c38c-72b6-4ff9-a0c1-09c09e93d028.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7090ee98-19d5-4d7c-8f0e-aba8d84fd42a.tmp.etl
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6b931244-23eb-401a-adb5-83684c27782c.tmp.csv
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f35ee554-9df9-44b9-bb63-992266d4df5c.tmp.txt
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.09e6073b-3093-44c0-bbb5-11e607716d97.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9d378650-a5bd-4763-bbbf-016a41ebd4df
Report Status: 268435456
Hashed bucket: ca0f8745ab8c5b7fba2f8ea4316864a7
Cab Guid: 0
```

### To Reproduce

Windows 11 Pro:
1. Download installer from OpenAdapt.AI website
2. Run Installer by opening installer
3. Run OpenAdapt by opening installed executable (e.g. via Start menu)
4. Observe no running application in system tray or task manager.
5. Open event viewer and click Find, "OpenAdapt"

**Comment by abrichr** [comment]
Verification form has been submitted at https://feedback.smartscreen.microsoft.com/feedback.aspx

**Comment by abrichr** [comment]
<img width="531" alt="image" src="https://github.com/user-attachments/assets/5690f533-2588-4b6c-a779-576f09185f0f">

**Comment by abrichr** [comment]
<img width="498" alt="image" src="https://github.com/user-attachments/assets/4bbb7e88-f5f8-48d5-add7-81b27acce4c1">
<img width="505" alt="image" src="https://github.com/user-attachments/assets/9532a9d3-f133-492c-8e23-12f340e62bd9">
<img width="503" alt="image" src="https://github.com/user-attachments/assets/66634bdc-dcd0-4b70-9d99-2999ae8edbc8">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/4102b05d-1e43-420e-8436-5f410d8d4d8b">
<img width="501" alt="image" src="https://github.com/user-attachments/assets/209861d8-d6eb-4d76-bc03-5c59a1fe3b0e">
<img width="849" alt="image" src="https://github.com/user-attachments/assets/8554bf1e-5df8-4bc5-8407-97a83dbb3818">

**Comment by abrichr** [comment]
```
pywinauto\__init__.py:80: UserWarning: Revert to STA COM threading mode
2024-10-28 15:42:23.544 | ERROR    | __main__:run_openadapt:27 - [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Roaming\\openadapt\\_internal\\tokencost\\model_prices.json'
Traceback (most recent call last):

  File "openadapt\entrypoint.py", line 31, in <module>
    run_openadapt()
    └ <function run_openadapt at 0x00000134F2EFB6D0>

> File "openadapt\entrypoint.py", line 19, in run_openadapt
    from openadapt.app import tray

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "openadapt\app\tray.py", line 45, in <module>
    from openadapt.strategies.base import BaseReplayStrategy

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "openadapt\strategies\__init__.py", line 7, in <module>
    from openadapt.strategies.base import BaseReplayStrategy

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "openadapt\strategies\base.py", line 10, in <module>
    from openadapt import adapters, models, playback, utils

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "openadapt\adapters\__init__.py", line 7, in <module>
    from . import prompt, replicate, som, ultralytics

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "openadapt\adapters\prompt.py", line 8, in <module>
    from openadapt.drivers import anthropic, google, openai

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "openadapt\drivers\openai.py", line 17, in <module>
    from tokencost import (

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "tokencost\__init__.py", line 1, in <module>

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "tokencost\costs.py", line 7, in <module>

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module

  File "tokencost\constants.py", line 54, in <module>

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Roaming\\openadapt\\_internal\\tokencost\\model_prices.json'
```
