### ISSUE TITLE
[Bug]: Build Issue

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#907]
### Describe the bug

```
Run poetry run python -m openadapt.build
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\a\OpenAdapt\OpenAdapt\openadapt\build.py", line 25, in <module>
    import ultralytics
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\ultralytics\__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, FastSAM, YOLOWorld
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\ultralytics\models\fastsam\__init__.py", line 3, in <module>
    from .model import FastSAM
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\ultralytics\models\fastsam\model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\ultralytics\engine\model.py", line 11, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\ultralytics\utils\__init__.py", line 22, in <module>
    import cv2
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-caElWqeS-py3.10\lib\site-packages\cv2\__init__.py", line [15](https://github.com/OpenAdaptAI/OpenAdapt/actions/runs/11555312502/job/32234633770#step:6:16)3, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: %1 is not a valid Win32 application.
Set-Location: D:\a\_temp\e40b2fee-3c25-4ce8-ac7f-2e987d1c6799.ps1:3
Line |
   3 |  cd dist
     |  ~~~~~~~
     | Cannot find path 'D:\a\OpenAdapt\OpenAdapt\dist' because it does not exist.
Error: Process completed with exit code 1.
```

### To Reproduce

https://github.com/OpenAdaptAI/OpenAdapt/actions/runs/11555312502/job/32234633770

**Comment by abrichr** [comment]
Appears to have been fixed in https://github.com/OpenAdaptAI/OpenAdapt/pull/905
