### ISSUE TITLE
Running python -m puterbot.visualize gives an IndexError

### ISSUE THREAD

**Issue by Jonathan-Sendsen** [OpenAdaptAI/OpenAdapt#94]
When I run `python -m puterbot.visualize  I get this error (see below). I don’t get a browser window that opens. When I took a screen shot with another recording I still  get the same error

![Screenshot 2023-05-06 at 6 29 54 PM](https://user-images.githubusercontent.com/38477076/236647731-c97ef137-cebf-4c79-a21a-740120977c5b.png)

**Comment by abrichr** [comment]
Thanks @Jonathan-Sendsen ! Can you please copy and paste the full console output from your recording? Please include it as text and not a screenshot. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code for instructions on how to format.

Thank you!! 🙏

**Comment by Jonathan-Sendsen** [comment]
@abrichr after running ``` python -m puterbot.visualize```  I receive the below output from my console 

```
(base) ➜  puterbot git:(main) python -m puterbot.visualize

Traceback (most recent call last):
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/visualize.py", line 226, in <module>
    main()
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/visualize.py", line 135, in main
    input_events = get_events(recording, process=PROCESS_EVENTS, meta=meta)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/events.py", line 30, in get_events
    screenshots = get_screenshots(recording)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/crud.py", line 109, in get_screenshots
    screenshots[0].prev = screenshots[0]
IndexError: list index out of range 
```

Below you will find the console output from my full recording 
```

(base) ➜  puterbot git:(main) python -m puterbot.record "testing out puterbot"

2023-05-06 18:54:03.463 | INFO     | __main__:record:581 - task_description='testing out puterbot'
2023-05-06 18:54:03.523 | INFO     | __main__:create_recording:518 - recording=Recording(id=5, timestamp=1683410043.463653, monitor_width=1440, monitor_height=900, double_click_interval_seconds=0.5, double_click_distance_pixels=5, platform='darwin', task_description='testing out puterbot')
2023-05-06 18:54:03.570 | INFO     | __main__:read_screen_events:360 - starting
2023-05-06 18:54:03.579 | INFO     | __main__:read_window_events:386 - starting
2023-05-06 18:54:03.579 | INFO     | __main__:read_window_events:386 - starting
2023-05-06 18:54:03.591 | INFO     | __main__:process_events:91 - starting
This process is not trusted! Input event monitoring will not be possible until it is added to accessibility clients.
2023-05-06 18:54:03.659 | WARNING  | __main__:read_window_events:398 - geometry=None
2023-05-06 18:54:03.664 | INFO     | __main__:read_window_events:416 - title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×56' prev_title=None geometry=(721.0, 28.0, 717.0, 819.0) prev_geometry=None
This process is not trusted! Input event monitoring will not be possible until it is added to accessibility clients.
2023-05-06 18:54:05.153 | INFO     | __main__:read_window_events:416 - title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' prev_title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×56' geometry=(721.0, 28.0, 717.0, 819.0) prev_geometry=(721.0, 28.0, 717.0, 819.0)
2023-05-06 18:54:05.219 | INFO     | __main__:read_window_events:416 - title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' prev_title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' geometry=(721.0, 28.0, 717.0, 875.0) prev_geometry=(721.0, 28.0, 717.0, 819.0)
2023-05-06 18:54:05.236 | INFO     | __main__:read_window_events:416 - title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' prev_title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' geometry=(720.0, 25.0, 717.0, 875.0) prev_geometry=(721.0, 28.0, 717.0, 875.0)
2023-05-06 18:54:05.260 | INFO     | __main__:read_window_events:416 - title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' prev_title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' geometry=(721.0, 25.0, 717.0, 875.0) prev_geometry=(720.0, 25.0, 717.0, 875.0)
2023-05-06 18:54:05.946 | INFO     | __main__:read_window_events:416 - title='Google Chrome MLDSAI/puterbot: AI-First Process Automation with Transformers' prev_title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' geometry=(0.0, 25.0, 720.0, 825.0) prev_geometry=(721.0, 25.0, 717.0, 875.0)
2023-05-06 18:54:06.435 | INFO     | __main__:read_window_events:416 - title='Google Chrome MLDSAI/puterbot: AI-First Process Automation with Transformers' prev_title='Google Chrome MLDSAI/puterbot: AI-First Process Automation with Transformers' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 825.0)
2023-05-06 18:54:06.793 | INFO     | __mp_main__:write_events:230 - event_type='input' starting
2023-05-06 18:54:06.793 | INFO     | __mp_main__:write_events:230 - event_type='screen' starting
2023-05-06 18:54:06.793 | INFO     | __mp_main__:write_events:230 - event_type='window' starting
2023-05-06 18:54:10.803 | WARNING  | __main__:read_window_events:398 - geometry=None
2023-05-06 18:54:10.839 | INFO     | __main__:read_window_events:416 - title='Google Chrome New Tab' prev_title='Google Chrome MLDSAI/puterbot: AI-First Process Automation with Transformers' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:54:11.861 | INFO     | __main__:read_window_events:416 - title='Google Chrome ' prev_title='Google Chrome New Tab' geometry=(86.0, 51.0, 420.0, 376.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:54:12.013 | INFO     | __main__:read_window_events:416 - title='Google Chrome ' prev_title='Google Chrome ' geometry=(86.0, 51.0, 420.0, 387.0) prev_geometry=(86.0, 51.0, 420.0, 376.0)
2023-05-06 18:54:13.009 | INFO     | __main__:read_window_events:416 - title='Google Chrome ' prev_title='Google Chrome ' geometry=(86.0, 51.0, 420.0, 376.0) prev_geometry=(86.0, 51.0, 420.0, 387.0)
2023-05-06 18:54:14.955 | INFO     | __main__:read_window_events:416 - title='Google Chrome New Tab' prev_title='Google Chrome ' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(86.0, 51.0, 420.0, 376.0)
2023-05-06 18:54:16.390 | INFO     | __main__:read_window_events:416 - title='Google Chrome Figma' prev_title='Google Chrome New Tab' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:54:17.656 | INFO     | __main__:read_window_events:416 - title='Google Chrome outloud - Google Search' prev_title='Google Chrome Figma' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:54:18.944 | INFO     | __main__:read_window_events:416 - title='Google Chrome Figma' prev_title='Google Chrome outloud - Google Search' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:54:18.968 | INFO     | __main__:read_window_events:416 - title='Google Chrome ' prev_title='Google Chrome Figma' geometry=(-1.0, 879.0, 240.0, 22.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:54:23.906 | INFO     | __main__:read_window_events:416 - title='Google Chrome Tribe_hackathon – Figma' prev_title='Google Chrome ' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(-1.0, 879.0, 240.0, 22.0)
2023-05-06 18:54:37.475 | INFO     | __main__:read_window_events:416 - title='Google Chrome MLDSAI/puterbot: AI-First Process Automation with Transformers' prev_title='Google Chrome Tribe_hackathon – Figma' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:54:41.158 | INFO     | __main__:read_window_events:416 - title='Google Chrome ' prev_title='Google Chrome MLDSAI/puterbot: AI-First Process Automation with Transformers' geometry=(450.0, 62.0, 270.0, 74.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:54:44.110 | INFO     | __main__:read_window_events:416 - title='Google Chrome ' prev_title='Google Chrome ' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(450.0, 62.0, 270.0, 74.0)
2023-05-06 18:54:44.117 | INFO     | __main__:read_window_events:416 - title='Google Chrome Tribe_hackathon – Figma' prev_title='Google Chrome ' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:55:01.746 | INFO     | __main__:read_window_events:416 - title='Google Chrome MLDSAI/puterbot: AI-First Process Automation with Transformers' prev_title='Google Chrome Tribe_hackathon – Figma' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:55:04.452 | INFO     | __main__:read_window_events:416 - title='Google Chrome ' prev_title='Google Chrome MLDSAI/puterbot: AI-First Process Automation with Transformers' geometry=(450.0, 62.0, 270.0, 74.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:55:08.435 | INFO     | __main__:read_window_events:416 - title='Google Chrome ' prev_title='Google Chrome ' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(450.0, 62.0, 270.0, 74.0)
2023-05-06 18:55:08.438 | INFO     | __main__:read_window_events:416 - title='Google Chrome Tribe_hackathon – Figma' prev_title='Google Chrome ' geometry=(0.0, 25.0, 720.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
2023-05-06 18:55:12.722 | INFO     | __main__:read_window_events:416 - title='Terminal puterbot — python -m puterbot.record "testing out puterbot" — python — python ◂ python -m puterbot.record testing out puterbot — 101×60' prev_title='Google Chrome Tribe_hackathon – Figma' geometry=(721.0, 25.0, 717.0, 875.0) prev_geometry=(0.0, 25.0, 720.0, 875.0)
^C2023-05-06 18:55:13.990 | INFO     | __main__:record:679 - joining...
2023-05-06 18:55:13.990 | INFO     | __mp_main__:write_events:239 - event_type='input' done
2023-05-06 18:55:13.990 | INFO     | __mp_main__:write_events:239 - event_type='window' done
2023-05-06 18:55:13.990 | INFO     | __mp_main__:write_events:239 - event_type='screen' done
Exception in thread Thread-5 (read_mouse_events):
Traceback (most recent call last):
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2023-05-06 18:55:14.017 | INFO     | __main__:read_screen_events:367 - done
2023-05-06 18:55:14.020 | INFO     | __main__:process_events:145 - done
    self.run()
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jonathansendsen/Desktop/puterbot/puterbot/record.py", line 566, in read_mouse_events
    mouse_listener.stop()
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/site-packages/pynput/_util/__init__.py", line 187, in stop
    self._stop_platform()
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/site-packages/pynput/_util/darwin.py", line 237, in _stop_platform
    Quartz.CFRunLoopStop(self._loop)
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/site-packages/objc/_lazyimport.py", line 168, in __getattr__
    value = getattr(p, name)
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/site-packages/objc/_lazyimport.py", line 168, in __getattr__
    value = getattr(p, name)
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/site-packages/objc/_lazyimport.py", line 186, in __getattr__
    value = self.__get_constant(name)
  File "/Users/jonathansendsen/anaconda3/lib/python3.10/site-packages/objc/_lazyimport.py", line 412, in __get_constant
    self.__funcmap.pop(name)
KeyError: 'CFRunLoopStop'
```

**Comment by abrichr** [comment]
Thank you @Jonathan-Sendsen ! Can you please select Apple Menu -> "About This Mac", take a screenshot of your system information and post it here?

Also, can you please clarify whether you encountered this error? https://github.com/MLDSAI/puterbot#troubleshooting

**Comment by flyguy712** [comment]
@abrichr I have also run into this issue:

```
(.venv) taylorhorsager@Taylors-MacBook-Air puterbot % python -m puterbot.visualize
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/taylorhorsager/OpenAdapt/puterbot/visualize.py", line 226, in <module>
    main()
  File "/Users/taylorhorsager/OpenAdapt/puterbot/visualize.py", line 135, in main
    input_events = get_events(recording, process=PROCESS_EVENTS, meta=meta)
  File "/Users/taylorhorsager/OpenAdapt/puterbot/events.py", line 30, in get_events
    screenshots = get_screenshots(recording)
  File "/Users/taylorhorsager/OpenAdapt/puterbot/crud.py", line 109, in get_screenshots
    screenshots[0].prev = screenshots[0]
IndexError: list index out of range
```

Here are my computer specs: 

<img width="272" alt="Screenshot 2023-05-07 at 7 19 17 PM" src="https://user-images.githubusercontent.com/84868895/236713868-1415cac7-2fb8-4dd6-8922-f90c4d63195a.png">

**Comment by abrichr** [comment]
@micol-altomare do you have a macbook? If so perhaps you could try to recreate this issue.

**Comment by AvidEslami** [comment]
From my experience in testing, this error occurs whenever an incomplete recording was made or no recording was present, not sure if this helps but just something I've noticed. This occurred for me when starting replay.py and immediately interrupting it

**Comment by 0dm** [comment]
> From my tests, this error occurs whenever an incomplete recording was made or no recording was present, not sure if this helps but just something I've noticed. This occurred for me when starting replay.py and immediately interrupting it. On windows running vscode as administrator helped.

I think you're right.

**Comment by abrichr** [comment]
@Jonathan-Sendsen @flyguy712 the workaround is to create a valid recording. Can you please follow the instructions exactly as written in https://github.com/MLDSAI/OpenAdapt#record ?

**Comment by FFFiend** [comment]
I'm moving my cursor and typing words into the terminal, but I still face this error.

**Comment by apgorton** [comment]
@FFFiend Can you check the db after you have made a recording and see if it has data, namely screenshots for the recording?

We should put a check in get_screenshots() raise an exception and log a more helpful error for the user there or in the caller.

**Comment by Jonathan-Sendsen** [comment]
Currently blocked by https://github.com/MLDSAI/OpenAdapt/issues/96 my environment was whack so had to reconfigure it.

**Comment by FFFiend** [comment]
> @FFFiend Can you check the db after you have made a recording and see if it has data, namely screenshots for the recording?
> 
> We should put a check in get_screenshots() raise an exception and log a more helpful error for the user there or in the caller.


Yep just checked, screenshots is indeed empty. It's weird though, I'm following all steps and still it returns an empty list

**Comment by 0dm** [comment]
@FFFiend Would you like to get on a call and share your screen with me? I can do any time tonight.

**Comment by FFFiend** [comment]
@0dm sure, I'll let you know what time works best a bit later :D

**Comment by abrichr** [comment]
Closing as part of architecture transition. Legacy frozen at v0.46.0. See PR #960.
