### ISSUE TITLE
Attempting to install puterbot gives legacy-install-error

### ISSUE THREAD

**Issue by Jonathan-Sendsen** [OpenAdaptAI/OpenAdapt#97]
```  × Running setup.py install for pynput did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-5wlogsqp/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/jonathansendsen/puterbot/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-5wlogsqp/.eggs/wrapt-1.15.0-py3.10-macosx-10.9-universal2.egg/wrapt-1.15.0.dist-info' -> '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-5wlogsqp/.eggs/wrapt-1.15.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure```

**Comment by Jonathan-Sendsen** [comment]
Just to add more context to the above. When attempting to install:

```
git clone https://github.com/MLDSAI/OpenAdapt.git
cd OpenAdapt
python3.10 -m venv .venv
source .venv/bin/activate
pip install wheel
pip install -r requirements.txt
pip install -e .
alembic upgrade head
pytest
```


I get this error on my terminal:



```     /Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-bn5uj7na/setup.py", line 87, in <module>
          setuptools.setup(
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-bn5uj7na/.eggs/wrapt-1.15.0-py3.10-macosx-10.9-universal2.egg/wrapt-1.15.0.dist-info' -> '/private/var/folders/33/g_h_rt791rvdrpm4xrhbn_8r0000gn/T/pip-req-build-bn5uj7na/.eggs/wrapt-1.15.0-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pynput

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Obtaining file:///Users/jonathansendsen/puterbot/OpenAdapt
  Preparing metadata (setup.py) ... done
Installing collected packages: puterbot
  Running setup.py develop for puterbot
Successfully installed puterbot-0.1.0

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/jonathansendsen/puterbot/OpenAdapt/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/jonathansendsen/puterbot/OpenAdapt/alembic/env.py", line 22, in <module>
    from puterbot.models import *
  File "/Users/jonathansendsen/puterbot/OpenAdapt/./puterbot/models.py", line 4, in <module>
    from pynput import keyboard
ModuleNotFoundError: No module named 'pynput'
============================================ test session starts =============================================
platform darwin -- Python 3.10.10, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/jonathansendsen/puterbot/OpenAdapt
collected 0 items / 1 error                                                                                  

=================================================== ERRORS ===================================================
_______________________________ ERROR collecting tests/puterbot/test_events.py _______________________________
ImportError while importing test module '/Users/jonathansendsen/puterbot/OpenAdapt/tests/puterbot/test_events.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/puterbot/test_events.py:9: in <module>
    from puterbot.models import InputEvent, WindowEvent
puterbot/models.py:4: in <module>
    from pynput import keyboard
E   ModuleNotFoundError: No module named 'pynput'
========================================== short test summary info ===========================================
ERROR tests/puterbot/test_events.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================= 1 error in 10.42s ==============================================```

**Comment by abrichr** [comment]
Please try the solutions mentioned in this thread: https://github.com/MLDSAI/OpenAdapt/issues/40

Isn't this the same issue as https://github.com/MLDSAI/OpenAdapt/issues/96 ?

**Comment by Jonathan-Sendsen** [comment]
Not sure if a `subprocess-exited-with-error` and a legacy-install-error` are the same or not but i'll give #40 a closer look shortly
